import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CalendarDays, MapPin } from "lucide-react";
import { usePublicEvent } from "../hooks/usePublicEvent";
import { formatKoreanDate } from "../lib/formatDate";

export function EventGuide() {
  const { eventId } = useParams();
  const { event, loading, error } = usePublicEvent(eventId);
  return <main className="min-h-dvh bg-app-background px-4 py-6 text-app-ink"><section className="phone-surface overflow-hidden rounded-[28px] border border-app-border shadow-phone"><header className="border-b border-app-border bg-white px-4 pb-4 pt-3"><div className="mx-auto mb-3 h-1 w-16 rounded-full bg-slate-300" /><div className="flex items-center justify-between"><Link to={`/e/${eventId}`} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><ArrowLeft className="h-5 w-5" /></Link><h1 className="text-base font-black">행사 안내</h1><div className="h-10 w-10" /></div></header><div className="flex-1 space-y-4 bg-slate-50 p-4">{loading && <div className="card p-5 text-center text-sm font-black text-app-muted">불러오는 중</div>}{error && <div className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{event && <><section className="rounded-panel bg-app-ink p-5 text-white"><p className="text-[11px] font-black text-slate-400">EVENT GUIDE</p><h2 className="mt-2 text-2xl font-black">{event.title}</h2>{event.subtitle && <p className="mt-2 text-sm font-bold text-slate-300">{event.subtitle}</p>}</section>{event.scheduledAt && <section className="card flex items-center gap-3 p-4"><CalendarDays className="h-5 w-5 text-app-primary" /><div><p className="text-xs font-black text-app-muted">행사 일정</p><p className="mt-1 text-sm font-black">{formatKoreanDate(event.scheduledAt)}</p></div></section>}<section className="card p-4"><h2 className="text-sm font-black">장소·활동 안내</h2><div className="mt-3 divide-y divide-app-border">{event.places.map((place) => <div key={place.id} className="py-3"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-app-primary" /><strong className="text-sm font-black">{place.name}</strong></div>{place.description && <p className="mt-1 pl-6 text-xs font-bold leading-5 text-app-muted">{place.description}</p>}{place.mapUrl && <a href={place.mapUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block pl-6 text-xs font-black text-app-primary">지도에서 보기</a>}</div>)}</div></section></>}</div></section></main>;
}
